# Based on https://github.com/flathub/com.github.wwmm.easyeffects/blob/ee41024da8cf4a8c40d529737e3991c87ad6501b/.github/workflows/update-beta.yml

name: Check for stable updates in master branch
on:
  schedule:
  - cron: "0 * * * *" # run every hour, a scheduled workflow only runs if in the default branch.
  workflow_dispatch:

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub/flatpak-external-data-checker

    steps:
      - uses: actions/checkout@v2
        with:
          ref: beta # with this workflow, f-e-d-c will specifically checkout and submit a PR against beta, not master.

      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork com.github.Anuken.Mindustry.yml
